# frozen_string_literal: true

source "https://rubygems.org"

#git_source(:github) {|v-sr/blog.git| "https://github.com/#{v-sr/blog.git}" }

# gem "rails"
gem "github-pages", "~> 204", group: :jekyll_plugins
